kafka-manager:
  image: huanqingdong/kafka-manager:1.3.3.23
  container_name: kafka-manager
  ports:
    - "9000:9000"
  environment:
    ZK_HOSTS: 192.168.1.14:2181
    KM_USERNAME: admin
    KM_PASSWORD: admin
