zookeeper:
  image: zookeeper
  container_name: zk-for-km

kafka-manager:
  image: huanqingdong/kafka-manager:1.3.3.23
  container_name: kafka-manager
  ports:
    - "9000:9000"
  links:
    - zookeeper
  environment:
    ZK_HOSTS: zookeeper:2181
    APPLICATION_SECRET: faith
    KM_ARGS: -Djava.net.preferIPv4Stack=true
